spring:
  application:
    name: employee

  # Database config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee?currentSchema=public
    username: postgres
    password: postgres
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  # Liquibase config
  liquibase:
    enabled: false
#    change-log: classpath:common_changelog.xml

# Eureka config
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} # default-ный url сервиса
  instance:
    hostname: my-eureka-server.com # host эврики (если сервер и клиент расположены не на Localhost)

feign:
  hystrix:
    enabled: true